name: untitled
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
#  path: ^1.7.0
  socket_io: ^0.9.2

#dev_dependencies:
#  test: ^1.14.4
